OrdererOrgs:
  - Name: Orderer
    Domain: property-registration-network.com
    Specs:
      - Hostname: orderer
PeerOrgs:
 - Name: beneficiary
   Domain: beneficiary.property-registration-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: agent
   Domain: agent.property-registration-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: government
   Domain: government.property-registration-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
 - Name: buyer
   Domain: buyer.property-registration-network.com
   EnableNodeOUs: true
   Template:
      Count: 2
   Users:
      Count: 1
