version: '2'

services:

  orderer.property-registration-network.com:
    container_name: orderer.property-registration-network.com
    image: hyperledger/fabric-orderer:latest
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enable TLS
      - ORDERER_GENERAL_TLS_ENABLED=false
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      #- GODEBUG=netdns=go
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/property-registration-network.com/orderers/orderer.property-registration-network.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/property-registration-network.com/orderers/orderer.property-registration-network.com/tls/:/var/hyperledger/orderer/tls
    - orderer.property-registration-network.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.beneficiary.property-registration-network.com:
    container_name: peer0.beneficiary.property-registration-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.beneficiary.property-registration-network.com
      - CORE_PEER_ADDRESS=peer0.beneficiary.property-registration-network.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.beneficiary.property-registration-network.com:7053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7053
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.beneficiary.property-registration-network.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.beneficiary.property-registration-network.com:7051
      - CORE_PEER_LOCALMSPID=beneficiaryMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/beneficiary.property-registration-network.com/peers/peer0.beneficiary.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/beneficiary.property-registration-network.com/peers/peer0.beneficiary.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.beneficiary.property-registration-network.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.beneficiary.property-registration-network.com:
    container_name: peer1.beneficiary.property-registration-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.beneficiary.property-registration-network.com
      - CORE_PEER_ADDRESS=peer1.beneficiary.property-registration-network.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer0.beneficiary.property-registration-network.com:8053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.beneficiary.property-registration-network.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.beneficiary.property-registration-network.com:7051
      - CORE_PEER_LOCALMSPID=beneficiaryMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/beneficiary.property-registration-network.com/peers/peer1.beneficiary.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/beneficiary.property-registration-network.com/peers/peer1.beneficiary.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.beneficiary.property-registration-network.com:/var/hyperledger/production

    ports:
      - 8051:8051
      - 8053:8053

  peer0.agent.property-registration-network.com:
    container_name: peer0.agent.property-registration-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.agent.property-registration-network.com
      - CORE_PEER_ADDRESS=peer0.agent.property-registration-network.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.agent.property-registration-network.com:9053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.agent.property-registration-network.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.agent.property-registration-network.com:10051
      - CORE_PEER_LOCALMSPID=agentMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/agent.property-registration-network.com/peers/peer0.agent.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/agent.property-registration-network.com/peers/peer0.agent.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.agent.property-registration-network.com:/var/hyperledger/production
    ports:
      - 9051:9051
      - 9053:9053

  peer1.agent.property-registration-network.com:
    container_name: peer1.agent.property-registration-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.agent.property-registration-network.com
      - CORE_PEER_ADDRESS=peer1.agent.property-registration-network.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer0.agent.property-registration-network.com:10053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.agent.property-registration-network.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.agent.property-registration-network.com:9051
      - CORE_PEER_LOCALMSPID=agentMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/agent.property-registration-network.com/peers/peer1.agent.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/agent.property-registration-network.com/peers/peer1.agent.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.agent.property-registration-network.com:/var/hyperledger/production
    ports:
      - 10051:10051
      - 10053:10053

  peer0.government.property-registration-network.com:
    container_name: peer2.government.property-registration-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.government.property-registration-network.com
      - CORE_PEER_ADDRESS=peer0.government.property-registration-network.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.government.property-registration-network.com:11053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.government.property-registration-network.com:11051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.government.property-registration-network.com:9051
      - CORE_PEER_LOCALMSPID=governmentMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/government.property-registration-network.com/peers/peer0.government.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/government.property-registration-network.com/peers/peer0.government.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.government.property-registration-network.com:/var/hyperledger/production
    ports:
      - 11051:11051
      - 11053:11053

  peer1.government.property-registration-network.com:
    container_name: peer1.government.property-registration-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.government.property-registration-network.com
      - CORE_PEER_ADDRESS=peer1.government.property-registration-network.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer0.government.property-registration-network.com:12053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.government.property-registration-network.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.government.property-registration-network.com:9051
      - CORE_PEER_LOCALMSPID=governmentMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/government.property-registration-network.com/peers/peer1.government.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/government.property-registration-network.com/peers/peer1.government.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.government.property-registration-network.com:/var/hyperledger/production
    ports:
      - 12051:12051
      - 12053:12053

  peer0.buyer.property-registration-network.com:
    container_name: peer0.buyer.property-registration-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.buyer.property-registration-network.com
      - CORE_PEER_ADDRESS=peer0.buyer.property-registration-network.com:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_CHAINCODEADDRESS=peer0.buyer.property-registration-network.com:13053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.buyer.property-registration-network.com:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.buyer.property-registration-network.com:9051
      - CORE_PEER_LOCALMSPID=buyerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/buyer.property-registration-network.com/peers/peer0.buyer.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/buyer.property-registration-network.com/peers/peer0.buyer.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer0.buyer.property-registration-network.com:/var/hyperledger/production
    ports:
      - 13051:13051
      - 13053:13053
  
  peer1.buyer.property-registration-network.com:
    container_name: peer1.buyer.property-registration-network.com
    extends:
      file: docker-compose-peer.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.buyer.property-registration-network.com
      - CORE_PEER_ADDRESS=peer1.buyer.property-registration-network.com:14051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_PEER_CHAINCODEADDRESS=peer0.buyer.property-registration-network.com:14053
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:14053
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.buyer.property-registration-network.com:14051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.buyer.property-registration-network.com:9051
      - CORE_PEER_LOCALMSPID=buyerMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/buyer.property-registration-network.com/peers/peer1.buyer.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/buyer.property-registration-network.com/peers/peer1.buyer.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
        - peer1.buyer.property-registration-network.com:/var/hyperledger/production
    ports:
      - 14051:14051
      - 14053:14053
  # peer0.upgrad.property-registration-network.com:
  #   container_name: peer0.upgrad.property-registration-network.com
  #   extends:
  #     file: docker-compose-peer.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer0.upgrad.property-registration-network.com
  #     - CORE_PEER_ADDRESS=peer0.upgrad.property-registration-network.com:11051
  #     - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
  #     - CORE_PEER_CHAINCODEADDRESS=peer0.upgrad.property-registration-network.com:11053
  #     - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11053
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.upgrad.property-registration-network.com:11051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.upgrad.property-registration-network.com:12051
  #     - CORE_PEER_LOCALMSPID=upgradMSP
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ../crypto-config/peerOrganizations/upgrad.property-registration-network.com/peers/peer0.upgrad.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
  #       - ../crypto-config/peerOrganizations/upgrad.property-registration-network.com/peers/peer0.upgrad.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
  #       - peer0.upgrad.property-registration-network.com:/var/hyperledger/production
  #   ports:
  #     - 11051:11051
  #     - 11053:11053

  # peer1.upgrad.property-registration-network.com:
  #   container_name: peer1.upgrad.property-registration-network.com
  #   extends:
  #     file: docker-compose-peer.yaml
  #     service: peer-base
  #   environment:
  #     - CORE_PEER_ID=peer1.upgrad.property-registration-network.com
  #     - CORE_PEER_ADDRESS=peer1.upgrad.property-registration-network.com:12051
  #     - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
  #     - CORE_PEER_CHAINCODEADDRESS=peer0.upgrad.property-registration-network.com:12053
  #     - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12053
  #     - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.upgrad.property-registration-network.com:12051
  #     - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.upgrad.property-registration-network.com:11051
  #     - CORE_PEER_LOCALMSPID=upgradMSP
  #   volumes:
  #       - /var/run/:/host/var/run/
  #       - ../crypto-config/peerOrganizations/upgrad.property-registration-network.com/peers/peer1.upgrad.property-registration-network.com/msp:/etc/hyperledger/fabric/msp
  #       - ../crypto-config/peerOrganizations/upgrad.property-registration-network.com/peers/peer1.upgrad.property-registration-network.com/tls:/etc/hyperledger/fabric/tls
  #       - peer1.upgrad.property-registration-network.com:/var/hyperledger/production
  #   ports:
  #     - 12051:12051
  #     - 12053:12053
